### ISSUE TITLE
OS X El Capitan black mask

### ISSUE THREAD

**Issue by isinkler** [SWI-Prolog/issues#30]
I'm having issues with the interface on El Capitan. The text has a black mask on it, and can't be read.
![screen shot 2015-10-26 at 11 40 21](https://cloud.githubusercontent.com/assets/4548581/10725663/63466440-7bd6-11e5-85df-324694673993.png)

**Comment by JanWielemaker** [comment]
This is already under discussion on the mailinglist.  A solution is not yet known.  See e.g.
https://groups.google.com/forum/#!topic/swi-prolog/hzcG1QWEe1A

**Comment by JanWielemaker** [comment]
I just updated my _early 2008 iMac_ to El Captain.  None of the issues with SWI-Prolog on El Captain reproduce.   Now we get the interesting task to find the difference between the working and failing Macs.  So, working:

| Property | Value |
| ------------|--------------------------------------------|
| Model      | iMac (20 inch, Early 2008)            |
| Graphics | ATI Radeon HD 2600 Pro 256 MB |
| OS          | 10.11.1 (El Captain)                       |
| Font        | English/Courier/Regular/14            |
| XQuartz  | 2.7.8                                               |

Notes

  - For Model/Graphcs/OS, use __Apple/About this Mac__
  - For Font, start the SWI-Prolog app and use __Settings/Font ...__
  - XQuartz is not relevant for this, but various people also report the X11 IDE does not work.
    Test using `?- emacs.`  Might take *minutes* the first time.  Should be fast afterwards.

**Comment by pmoura** [comment]
I'm also using XQuartz 2.7.8. Font set to Courier/Regular/14 makes no difference. Still black bars in SWI-Prolog.app.

**Comment by pmoura** [comment]
I seem to remember that, the first time I started  SWI-Prolog.app, the text was readable but when setting a different font I got black bars and now I cannot get rid of them. This might point to a corruption issues when saving (or reusing from previous runs) application preferences.

**Comment by pmoura** [comment]
Confirmed: If you get black bard in SWI-Prolog.app, close the application, delete the file `~/Library/Preferences/com.swi-prolog.pqConsole.plist` and open the application again. The black bars should be gone. I modified the font settings, closed and reopened the application. No more problems. The issue may have originated in some incompatibility with preferences format from previous application versions.

**Comment by JanWielemaker** [comment]
Yes!  Except for one detail: if I change the font I get the black bars the next time I start SWI-Prolog.  Removing the preferences file gets it working again, but it breaks again when changing the font.  Tried several fonts.  That makes no difference.

Now, is this our fault, Qt or El Captain?

**Comment by nefuchs** [comment]
MacBook Pro (Retina, Mid 2012), OS X El Capitan 10.11.1, XQuartz 2.7.8
SWI Prolog 7.3.10 

Removing the file ~/Library/Preferences/com.swi-prolog.pqConsole.plist works for me, but only once. When I change the font – currently difficult to read Courier 12 –  in any way I get the black bars the next time I start SWI Prolog.

In any case, this is some progress and I would like to thank the people who work hard to eliminate this bug.

**Comment by JanWielemaker** [comment]
Fixed in 7.3.11.

**Comment by nefuchs** [comment]
> On 10 Nov 2015, at 17:33 , Jan Wielemaker <notifications@github.com> wrote:
> 
> Fixed in 7.3.11

Right, thank you.

   --- nef

**Comment by ruediarnold** [comment]
Hm, it's not fixed on my Mac. :-(
I have SWI-Prolog 7.3.28 with XQuartz 2.7.9 on a Mac Book Pro with El Cap (10.11.6).
Hints are much appreciated!

**Comment by nfrenchqub** [comment]
<img width="495" alt="screen shot 2016-11-07 at 18 02 15" src="https://cloud.githubusercontent.com/assets/18483198/20069412/57952010-a514-11e6-8ec5-1c4f12d11547.png">

Also having this problem on my rMBP Mid 2014 15", deleting the .plist didn't resolve the issue

**Comment by JanWielemaker** [comment]
I fear there is little hope for a solution as long as nobody manages to find a sequence to break it.  In the meanwhile, use the command line `swipl` that is in `Contents/MacOS/swipl` inside the app, or install using Homebrew or Macports.
